import bannerTools from "@/assets/images/banner-tools.png";
import bannerWarehouse from "@/assets/images/banner-warehouse.png";
import bannerMaterials from "@/assets/images/banner-materials.png";

export const mockCategorias = [
  { id: 1, nombre: "Maquinaria pesada" },
  { id: 2, nombre: "Equipos de apoyo" },
  { id: 3, nombre: "Repuestos" },
];

export const mockProductos = [
  {
    id: 101,
    nombre: "Excavadora compacta hidráulica",
    descripcion: "Equipo versátil para obra, zanjeo y movimiento de material en espacios reducidos.",
    categoria_id: 1,
    categoria_nombre: "Maquinaria pesada",
    precio: 1850,
    imagen_url: bannerTools,
    disponibilidad: "disponible",
    activo: true,
    cantidad: 4,
  },
  {
    id: 102,
    nombre: "Montacargas industrial",
    descripcion: "Maquinaria para carga, descarga y operación logística en bodegas industriales.",
    categoria_id: 1,
    categoria_nombre: "Maquinaria pesada",
    precio: 1250,
    imagen_url: bannerWarehouse,
    disponibilidad: "pocas_unidades",
    activo: true,
    cantidad: 2,
  },
  {
    id: 103,
    nombre: "Generador eléctrico industrial",
    descripcion: "Equipo de respaldo energético para proyectos, talleres y operaciones continuas.",
    categoria_id: 2,
    categoria_nombre: "Equipos de apoyo",
    precio: 780,
    imagen_url: bannerMaterials,
    disponibilidad: "disponible",
    activo: true,
    cantidad: 8,
  },
  {
    id: 104,
    nombre: "Compresor de aire para maquinaria",
    descripcion: "Compresor de alto rendimiento para herramientas neumáticas y mantenimiento.",
    categoria_id: 2,
    categoria_nombre: "Equipos de apoyo",
    precio: 420,
    imagen_url: bannerWarehouse,
    disponibilidad: "disponible",
    activo: true,
    cantidad: 6,
  },
  {
    id: 105,
    nombre: "Cilindro hidráulico reforzado",
    descripcion: "Componente de reemplazo para sistemas hidráulicos de equipo pesado.",
    categoria_id: 3,
    categoria_nombre: "Repuestos",
    precio: 260,
    imagen_url: bannerMaterials,
    disponibilidad: "pocas_unidades",
    activo: true,
    cantidad: 3,
  },
  {
    id: 106,
    nombre: "Accesorio de carga frontal",
    descripcion: "Implemento para maquinaria de carga y movimiento de materiales.",
    categoria_id: 3,
    categoria_nombre: "Repuestos",
    precio: 610,
    imagen_url: bannerTools,
    disponibilidad: "disponible",
    activo: true,
    cantidad: 5,
  },
];
