ALTER TABLE reservas
  ADD COLUMN IF NOT EXISTS tipo_tarifa TEXT NOT NULL DEFAULT 'dia',
  ADD COLUMN IF NOT EXISTS unidades_tarifa INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS precio_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_estimado NUMERIC(12, 2) NOT NULL DEFAULT 0;
